### ISSUE TITLE
Error: Process completed with exit code 1. Error message: ""

### ISSUE THREAD

**Issue by moghwan** [maxime1992/dev.to#11]
Hi,

I'm trying to publish a new post with the template but I suck with an empty error message while deploying to dev.to, I tried to post it as a draft with no content too but without success.

I removed embedme from yarn and actin but no success too but the old posts seems to be okay. 

```
Run DEV_TO_GIT_TOKEN=*** yarn run dev-to-git
yarn run v1.22.10
warning package.json: No license field
$ dev-to-git
[DRAFT] Article "Things you should know before starting Prestashop development" encountered an error:
Error name: "Error"
Error message: ""
Error stack: "Error
    at Article.<anonymous> (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:11180:39)
    at step (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:77:27)
    at Object.next (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:58:57)
    at fulfilled (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:48:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
[PUBLISHED] Article "Dockerize your Laravel project with Laradock" is already up to date
[PUBLISHED] Article "Is linux good enough for everyday programming?" is already up to date
[PUBLISHED] Article "Setup Prestashop CMS with Docker Compose" is already up to date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Did I something wrong? I think I;m missing something.

**Comment by moghwan** [comment]
I think it's related to travis migrating from .org to .com domain, now I'm trying to edit an older post and it gives me the 422 error as the log is saying:

```
Run DEV_TO_GIT_TOKEN=*** yarn run dev-to-git
yarn run v1.22.10
warning package.json: No license field
$ dev-to-git
[DRAFT] Article "Things you should know before starting Prestashop development" encountered an error:
Error name: "HTTPError"
Error message: "Response code 422 (Unprocessable Entity)"
Error stack: "HTTPError: Response code 422 (Unprocessable Entity)
    at EventEmitter.<anonymous> (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:7080:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
[PUBLISHED] Article "Dockerize your Laravel project with Laradock" encountered an error:
Error name: "HTTPError"
Error message: "Response code 422 (Unprocessable Entity)"
Error stack: "HTTPError: Response code 422 (Unprocessable Entity)
    at EventEmitter.<anonymous> (/home/runner/work/dev.to/dev.to/node_modules/dev-to-git/bin/dev-to-git.umd.js:7080:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
[PUBLISHED] Article "Is linux good enough for everyday programming?" is already up to date
[PUBLISHED] Article "Setup Prestashop CMS with Docker Compose" is already up to date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

I'm check the tokens an reconfigure the repos and see why exactly.

**Comment by maxime1992** [comment]
Hello, it's a known issue that you can follow/maybe help with here https://github.com/maxime1992/dev-to-git/issues/35
