### ISSUE TITLE
The command "yarn run embedme:check" exited with 1.

### ISSUE THREAD

**Issue by HDv2b** [maxime1992/dev.to#7]
After resolving the issues with prettier, I now get this on travis:

```
$ yarn run embedme:check
yarn run v1.15.2
warning package.json: No license field
$ yarn run embedme --verify
warning package.json: No license field
$ embedme blog-posts/**/*.md --verify
internal/modules/cjs/loader.js:670
    throw err;
    ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/travis/build/ElGoorf/dev.to/node_modules/embedme/dist/embedme.js:13:32)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run embedme:check" exited with 1.
```

**Comment by maxime1992** [comment]
:point_up: https://github.com/maxime1992/my-dev.to is my personal fork of https://github.com/maxime1992/dev.to, please report issues with the template on the latter :smiley_cat: 

(I've transferred the issue so all good for this one)

**Comment by maxime1992** [comment]
@zakhenry I think this might be an issue with https://github.com/zakhenry/embedme but not 100% sure. Can you confirm?

BTW sorry about the painful setup @ElGoorf but we're going to get you there :smile: !

**Comment by zakhenry** [comment]
@maxime1992 yep you're correct, I've fixed this in https://github.com/zakhenry/embedme/releases/tag/v1.17.1

Sorry about the confusion

**Comment by maxime1992** [comment]
Thanks @zakhenry :tada: 

@ElGoorf please upgrade embedme to `1.17.1` and let me know how it goes.

I'm closing this for now but feel free to reopen if needed.

**Comment by HDv2b** [comment]
looks like it's working, thanks! 🍻
